### PR TITLE
Various Changes From mstead

### PR DESCRIPTION
**Pull request by mstead**
**Move To Okaara**
python-click was a little handcuffing IMO. Although
okaara requires more boiler plate, it is a little
more flexible to pass around objects and whatnot.

I'm Ok with sticking with python-click if you feel strongly
for it.

**Added Configuration Framework**
Added a config framework that gets passed along. Config should
be in the ~/.trilla/trilla.yaml file.

See the commit log for an example.

**Added Hookup For Trello**
You can call the t_trello.config method to help you set up the
required configuration.

### CODE REVIEW

**Comment by vritant** [comment]
@mstead let me try it out this weekend.

**Comment by mstead** [comment]
I can break this up into multiple PRs but they kind of build off each other so I committed them together. Let me know if there's anything that should go away.

**Comment by vritant** [comment]
@mstead 
- I must say I did like Click, but perhaps there some advantages with okaara that I am missing? we can pass Config objects in click too, could you give an example of ways in which okaara will help us better?
- are there some dependencies missing?

>   File "/home/vjain/Code/trilla/trilla/t_trello.py", line 3, in <module>
>     from trello import TrelloClient, Board, Card
> ImportError: cannot import name TrelloClient

**Comment by mstead** [comment]
> are there some dependencies missing?

I added them to the requirements_dev.txt. I usually load that into my venv with pip.

**Comment by mstead** [comment]
> I must say I did like Click, but perhaps there some advantages with okaara that I am missing? we can pass Config objects in click too, could you give an example of ways in which okaara will help us better?

I'll see if I can get you an example tonight. It was command extension IIRC. I'll take a look tonight (if I get a chance) to revisit click. Shouldn't be too hard to port. I do remember hitting something that really handcuffed me -- hence the suggestion of moving to Okaara. Let me get back to you.

**Comment by vritant** [comment]
@mstead thoughts?

**Comment by vritant** [comment]
@mstead if we need to discuss the CLI change, perhaps do you mind placing another PR for the config bits? it could unblock me for other changes...

**Comment by mstead** [comment]
click will do just fine. I've backported the changes here to a new PR so I'm closing this one.

**Pull request closed without merging**
